-- MySQL Script generated by MySQL Workbench
-- 03/11/15 23:34:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET latin1 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`User` ;

CREATE TABLE IF NOT EXISTS `test`.`User` (
  `id_user` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` DATETIME NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Annonce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`Annonce` ;

CREATE TABLE IF NOT EXISTS `test`.`Annonce` (
  `titre_annonce` VARCHAR(45) NOT NULL,
  `contenu_annonce` VARCHAR(45) NOT NULL,
  `id_annonce` VARCHAR(45) NOT NULL,
  `date_de_creation` DATETIME NOT NULL,
  `id_annonceur` INT NOT NULL,
  `date_d_expiration` DATETIME NOT NULL,
  `date_debut` VARCHAR(45) NULL,
  `duree` VARCHAR(45) NULL,
  `genre_de_contrat` VARCHAR(45) NULL,
  `niveau_d_etude_requis` VARCHAR(45) NULL,
  `remuneration` VARCHAR(45) NULL,
  PRIMARY KEY (`id_annonce`),
  INDEX `fk_Annonce_User_idx` (`id_annonceur` ASC),
  CONSTRAINT `fk_Annonce_User`
    FOREIGN KEY (`id_annonceur`)
    REFERENCES `test`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`CV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`CV` ;

CREATE TABLE IF NOT EXISTS `test`.`CV` (
  `idCv` INT NOT NULL,
  `competence` VARCHAR(255) NULL,
  `dernier_diplome` VARCHAR(45) NULL,
  `annee_d_experience` VARCHAR(45) NULL,
  `langue` VARCHAR(255) NULL,
  `loisir` VARCHAR(45) NULL,
  `id_demandeur` INT NOT NULL,
  `competence_requise` VARCHAR(9000) NULL,
  PRIMARY KEY (`idCv`),
  INDEX `fk_CV_User1_idx` (`id_demandeur` ASC),
  CONSTRAINT `fk_CV_User1`
    FOREIGN KEY (`id_demandeur`)
    REFERENCES `test`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
